# Generated by Django 2.2.4 on 2020-06-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_profile_sms_verification'),
        ('dashboard', '0117_hackathonproject_extra'),
    ]

    operations = [
    ]
